---
- name: Run Insights Compliance Scanner
  hosts: all
  gather_facts: no

  tasks:
    - name: run insights compliance
      import_role:
        name: redhat.insights.compliance
        tasks_from: run