---
- name: Get users on server
  hosts: all

  tasks:
    - name: Get list of users
      getent:
        database: passwd
      register: getent_passwd
    
    - name: Print user list
      debug:
        msg: "{{ getent_passwd }}"